/** تجربة الجمعية الشريكة: مساحة تشغيلية هادئة تكشف التعطل وتوجّه التدخل قبل أن يحتاج المستفيد للسؤال. */
import { useEffect, useMemo, useState } from "react";
import { Link, useLocation, useRoute } from "wouter";
import { toast } from "sonner";
import { AppShell } from "@/components/AppShell";
import { StatusBadge, toneForStatus } from "@/components/StatusBadge";
import { associationCases, associationDemoThresholds, AssociationCase, stages } from "@/data";
import { AlertTriangle, ArrowLeft, BellRing, Building2, CalendarDays, CheckCircle2, ChevronLeft, CircleHelp, ClipboardCheck, Clock3, Filter, Flag, ListFilter, MessageSquareText, Search, ShieldAlert, UserRound, UsersRound, X } from "lucide-react";

type QueueTab = "الكل" | "تحتاج تدخل" | "متأخرة" | "تجاوزت مدة المرحلة" | "متطلبات ناقصة" | "جاهزة للانتقال";

const queueTabs: { label: QueueTab; count?: number }[] = [
  { label: "الكل" },
  { label: "تحتاج تدخل", count: 18 },
  { label: "متأخرة", count: 12 },
  { label: "تجاوزت مدة المرحلة", count: 7 },
  { label: "متطلبات ناقصة", count: 31 },
  { label: "جاهزة للانتقال", count: 23 },
];

function operationalSignals(item: AssociationCase) { const signals: string[] = []; if (item.requirement !== "مكتمل") signals.push("متطلب ناقص يمنع تقدم الطلب"); if (item.daysInStage > associationDemoThresholds.maxStageDays) signals.push("تجاوز الطلب المدة التجريبية للمرحلة"); if (item.daysSinceUpdate > associationDemoThresholds.maxDaysWithoutUpdate) signals.push(`لم يتم تحديث الحالة منذ ${item.daysSinceUpdate} يومًا`); return signals.length ? signals : [item.alert]; }

function formatFollowupDate(value: string) { return new Intl.DateTimeFormat("ar-SA", { day: "numeric", month: "long", year: "numeric" }).format(new Date(`${value}T12:00:00`)); }

const kpis = [
  { label: "إجمالي الحالات", value: "248", detail: "ضمن نطاق الجمعية", icon: <UsersRound size={18} />, tone: "mint" },
  { label: "تحتاج تدخل", value: "18", detail: "أولوية المتابعة اليوم", icon: <ShieldAlert size={18} />, tone: "orange" },
  { label: "متأخرة", value: "12", detail: "تجاوزت حد المتابعة", icon: <Clock3 size={18} />, tone: "stone" },
  { label: "تجاوزت مدة المرحلة", value: "7", detail: "بحاجة إلى مراجعة", icon: <Flag size={18} />, tone: "orange" },
  { label: "جاهزة للانتقال", value: "23", detail: "جاهزة للمراجعة", icon: <CheckCircle2 size={18} />, tone: "green" },
  { label: "متطلبات ناقصة", value: "31", detail: "تمنع تقدم الطلب", icon: <ClipboardCheck size={18} />, tone: "stone" },
];

function PriorityCard({ label, value, detail, onClick }: { label: string; value: string; detail: string; onClick: () => void }) {
  return <button className="association-priority-card" onClick={onClick}><span className="priority-value">{value}</span><span><strong>{label}</strong><small>{detail}</small></span><ArrowLeft size={17} /></button>;
}

function AssociationCaseRow({ item }: { item: AssociationCase }) {
  const [, navigate] = useLocation();
  return <article className="association-case-row" onClick={() => navigate(`/association/cases/${item.id}`)} role="button" tabIndex={0} onKeyDown={(event) => { if (event.key === "Enter") navigate(`/association/cases/${item.id}`); }}>
    <div className="association-case-person"><div className="case-avatar"><UserRound size={17} /></div><div><strong>{item.name}</strong><span>{item.id}</span></div></div>
    <div><small className="table-label">المرحلة الحالية</small><strong>{item.stage}</strong></div>
    <div><small className="table-label">مدة المرحلة</small><strong>{item.daysInStage} يومًا</strong></div>
    <div><StatusBadge tone={toneForStatus(item.status)}>{item.status}</StatusBadge><span className="case-subtext">{operationalSignals(item)[0]}</span></div>
    <div><small className="table-label">المسؤول الحالي</small><strong>{item.owner}</strong></div>
    <div className="association-case-action"><span>{item.action}</span><ChevronLeft size={16} /></div>
  </article>;
}

export function AssociationPage() {
  const [location, navigate] = useLocation();
  const [tab, setTab] = useState<QueueTab>("تحتاج تدخل");
  useEffect(() => { const view = new URLSearchParams(location.split("?")[1] ?? "").get("view"); const viewMap: Record<string, QueueTab> = { cases: "الكل", needs: "تحتاج تدخل", delayed: "متأخرة", ready: "جاهزة للانتقال", alerts: "تحتاج تدخل" }; if (view && viewMap[view]) setTab(viewMap[view]); }, [location]);
  const [query, setQuery] = useState("");
  const [stage, setStage] = useState("الكل");
  const [owner, setOwner] = useState("الكل");
  const [statusFilter, setStatusFilter] = useState("الكل");
  const [waitFilter, setWaitFilter] = useState("الكل");
  const [region, setRegion] = useState("الكل");
  const [updatedFilter, setUpdatedFilter] = useState("الكل");
  const filteredCases = useMemo(() => associationCases.filter((item) => {
    const matchesTab = tab === "الكل" || (tab === "تحتاج تدخل" ? item.priority === "تحتاج تدخل" : tab === "متأخرة" ? item.status === "متأخرة" : tab === "تجاوزت مدة المرحلة" ? item.status === "تجاوزت مدة المرحلة" : tab === "متطلبات ناقصة" ? item.status === "متطلبات ناقصة" : item.status === "جاهزة للانتقال");
    const matchesQuery = `${item.name} ${item.id}`.includes(query);
    const matchesStage = stage === "الكل" || item.stage === stage;
    const matchesOwner = owner === "الكل" || item.owner === owner;
    const matchesStatus = statusFilter === "الكل" || item.status === statusFilter;
    const matchesWait = waitFilter === "الكل" || (waitFilter === "أكثر من 7 أيام" ? item.daysInStage > 7 : item.daysInStage > 14);
    const matchesRegion = region === "الكل" || item.region === region;
    const matchesUpdated = updatedFilter === "الكل" || (updatedFilter === "بدون تحديث" ? item.daysSinceUpdate > associationDemoThresholds.maxDaysWithoutUpdate : item.daysSinceUpdate === 0);
    return matchesTab && matchesQuery && matchesStage && matchesOwner && matchesStatus && matchesWait && matchesRegion && matchesUpdated;
  }), [owner, query, region, stage, statusFilter, tab, updatedFilter, waitFilter]);
  return <AppShell variant="association" eyebrow="مساحة الجمعية · عرض تجريبي" title="جمعية الإسكان التنموي – الرياض" subtitle="متابعة الحالات المسندة للجمعية" actions={<button className="secondary-btn" onClick={() => navigate("/home")}>عرض المستفيد <ArrowLeft size={16} /></button>}>
    <div className="association-demo-banner"><BellRing size={16} /><strong>تنبيهات استرشادية</strong><span>هذه القواعد والحدود تجريبية لدعم المتابعة، ولا تمثل قرار أهلية أو أولوية رسميًا.</span></div>
    <section className="association-hero"><div><p className="eyebrow">الأولوية اليوم</p><h2>الحالات التي تحتاج انتباهك</h2><p>بدل انتظار المستفيد حتى يشتكي، ابدأ بالحالات التي يظهر فيها تعطل أو إجراء واضح.</p></div><div className="association-hero-mark"><span>18</span><small>حالة تحتاج تدخل</small></div></section>
    <section className="association-priority-grid"><PriorityCard label="تجاوزت مدة المرحلة" value="3" detail="تحتاج مراجعة اليوم" onClick={() => setTab("تجاوزت مدة المرحلة")} /><PriorityCard label="تحتاج استكمال متطلبات" value="5" detail="ينتظرها إجراء واضح" onClick={() => setTab("متطلبات ناقصة")} /><PriorityCard label="لم تُحدّث مؤخرًا" value="4" detail="افتح وسجل متابعة" onClick={() => setTab("متأخرة")} /></section>
    <section className="association-kpi-grid">{kpis.map((item) => <button key={item.label} className={`association-kpi ${item.tone}`} onClick={() => { if (item.label === "تحتاج تدخل") setTab("تحتاج تدخل"); if (item.label === "متأخرة") setTab("متأخرة"); if (item.label === "تجاوزت مدة المرحلة") setTab("تجاوزت مدة المرحلة"); if (item.label === "جاهزة للانتقال") setTab("جاهزة للانتقال"); if (item.label === "متطلبات ناقصة") setTab("متطلبات ناقصة"); }}><span className="kpi-icon">{item.icon}</span><span className="kpi-label">{item.label}</span><strong>{item.value}</strong><small>{item.detail}</small></button>)}</section>
    <section className="association-queue"><div className="association-section-heading"><div><p className="eyebrow">قائمة العمل</p><h2>مسار متابعة الطلبات</h2><p>مرشحات تشغيلية تساعدك على معرفة من يحتاج الإجراء التالي.</p></div><span className="mock-tag">بيانات تجريبية</span></div>
      <div className="association-tabs" role="tablist">{queueTabs.map((item) => <button key={item.label} className={tab === item.label ? "active" : ""} onClick={() => setTab(item.label)}>{item.label}{item.count && <b>{item.count}</b>}</button>)}</div>
      <div className="association-filter-bar"><label className="association-search"><Search size={16} /><input placeholder="ابحث باسم المستفيد أو رقم الطلب" value={query} onChange={(event) => setQuery(event.target.value)} /></label><label><ListFilter size={15} /><select value={stage} onChange={(event) => setStage(event.target.value)}><option value="الكل">كل المراحل</option><option>التخصيص</option><option>التحقق من البيانات</option><option>استكمال المتطلبات</option><option>استكمال الإجراءات</option></select></label><label><UserRound size={15} /><select value={owner} onChange={(event) => setOwner(event.target.value)}><option value="الكل">أي مسؤول</option><option>المستفيد</option><option>الجمعية</option><option>الجهة المختصة</option><option>مقدم الخدمة</option></select></label><label><Flag size={15} /><select value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)}><option value="الكل">حالة الطلب</option><option>تحتاج تدخل</option><option>متأخرة</option><option>تجاوزت مدة المرحلة</option><option>متطلبات ناقصة</option><option>جاهزة للانتقال</option><option>عادية</option></select></label><label><Clock3 size={15} /><select value={waitFilter} onChange={(event) => setWaitFilter(event.target.value)}><option value="الكل">مدة الانتظار</option><option>أكثر من 7 أيام</option><option>أكثر من 14 يومًا</option></select></label><label><Building2 size={15} /><select value={region} onChange={(event) => setRegion(event.target.value)}><option value="الكل">المنطقة</option><option>الرياض</option></select></label><label><CalendarDays size={15} /><select value={updatedFilter} onChange={(event) => setUpdatedFilter(event.target.value)}><option value="الكل">آخر تحديث</option><option>بدون تحديث</option><option>محدّث اليوم</option></select></label><button className="filter-reset" onClick={() => { setQuery(""); setStage("الكل"); setOwner("الكل"); setStatusFilter("الكل"); setWaitFilter("الكل"); setRegion("الكل"); setUpdatedFilter("الكل"); }}><Filter size={15} /> تصفية</button></div>
      <div className="quick-filter-row"><span>مرشحات سريعة:</span><button onClick={() => setTab("متأخرة")}>أكثر من 14 يومًا</button><button onClick={() => setTab("تجاوزت مدة المرحلة")}>أكثر من 7 أيام</button><button onClick={() => setTab("متطلبات ناقصة")}>ناقص مستند</button><button onClick={() => setTab("متأخرة")}>بدون تحديث</button></div>
      <div className="association-case-list">{filteredCases.length ? filteredCases.map((item) => <AssociationCaseRow item={item} key={item.id} />) : <div className="association-empty"><Search size={27} /><strong>لا توجد حالات بهذه التصفية</strong><p>ستظهر هنا الحالات التي تحتاج إجراءً ضمن نطاق الجمعية.</p><button onClick={() => { setTab("الكل"); setStage("الكل"); setOwner("الكل"); }}>عرض كل الحالات</button></div>}</div>
    </section>
    <div className="association-two-col"><section className="association-list-panel"><div className="association-section-heading compact"><div><p className="eyebrow">جاهزة للمراجعة</p><h2>حالات جاهزة للانتقال</h2></div><button className="text-link" onClick={() => setTab("جاهزة للانتقال")}>عرض الكل <ChevronLeft size={16} /></button></div>{associationCases.filter((item) => item.status === "جاهزة للانتقال").map((item) => <Link className="ready-case" href={`/association/cases/${item.id}`} key={item.id}><CheckCircle2 size={18} /><span><strong>{item.name}</strong><small>{item.id} · جميع المتطلبات مكتملة</small></span><ChevronLeft size={16} /></Link>)}</section><section className="association-list-panel"><div className="association-section-heading compact"><div><p className="eyebrow">تحتاج إجراء</p><h2>الحالات المتأخرة</h2></div><button className="text-link" onClick={() => setTab("متأخرة")}>عرض الكل <ChevronLeft size={16} /></button></div>{associationCases.filter((item) => item.priority === "تحتاج تدخل").slice(0, 3).map((item) => <Link className="delayed-case" href={`/association/cases/${item.id}`} key={item.id}><AlertTriangle size={18} /><span><strong>{item.name}</strong><small>{item.stage} · {item.daysInStage} يومًا · {item.owner}</small></span><ChevronLeft size={16} /></Link>)}</section></div>
    <section className="association-analytics"><div className="association-section-heading compact"><div><p className="eyebrow">مؤشرات المتابعة</p><h2>إشارات تشغيلية مختصرة</h2></div><span className="mock-tag">قيم تجريبية</span></div><div className="association-analytics-grid"><div><strong>11 يومًا</strong><span>متوسط مدة المرحلة</span></div><div><strong>18</strong><span>حالات تحتاج تدخل</span></div><div><strong>9</strong><span>حالات بدون تحديث</span></div><div><strong>2.4 يوم</strong><span>متوسط زمن إغلاق المتابعة</span></div><div><strong>82%</strong><span>حالات مكتملة المتطلبات</span></div></div><div className="bottleneck-strip"><span><b style={{ width: "100%" }} />التخصيص · 31</span><span><b style={{ width: "74%" }} />استكمال المتطلبات · 23</span><span><b style={{ width: "48%" }} />التحقق من البيانات · 15</span></div></section>
  </AppShell>;
}

function FollowupDrawer({ item, onClose, onSave }: { item: AssociationCase; onClose: () => void; onSave: (entry: { date: string; title: string; body: string; beneficiaryBody?: string; action?: string; responsible?: string; internal?: boolean }) => void }) {
  const [type, setType] = useState("متابعة مع الجهة");
  const [note, setNote] = useState("");
  const [needsAction, setNeedsAction] = useState("لا");
  const [nextAction, setNextAction] = useState("");
  const [responsible, setResponsible] = useState("الجمعية"); const [followupDate, setFollowupDate] = useState("2026-08-24");
  return <div className="drawer-backdrop" role="presentation"><aside className="association-drawer" role="dialog" aria-modal="true" aria-label="تسجيل متابعة"><button className="drawer-close" onClick={onClose} aria-label="إغلاق"><X size={20} /></button><p className="eyebrow">{item.id} · {item.name}</p><h2>تسجيل متابعة</h2><p className="drawer-intro">أضف إجراءً واضحًا إلى سجل الحالة حتى يعرف الفريق ما الذي حدث وما الخطوة التالية.</p><label>نوع المتابعة<select value={type} onChange={(event) => setType(event.target.value)}><option>اتصال بالمستفيد</option><option>مراجعة مستند</option><option>متابعة مع الجهة</option><option>تحديث حالة</option><option>ملاحظة داخلية</option></select></label><label>ملاحظة المتابعة<textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder="اكتب ملخصًا موجزًا لما تم..." /></label><label>هل يوجد إجراء آخر مطلوب؟<select value={needsAction} onChange={(event) => setNeedsAction(event.target.value)}><option>لا</option><option>نعم</option></select></label>{needsAction === "نعم" && <><label>الإجراء المطلوب<input value={nextAction} onChange={(event) => setNextAction(event.target.value)} placeholder="مثال: تحديث إثبات السكن" /></label><label>المسؤول<select value={responsible} onChange={(event) => setResponsible(event.target.value)}><option>المستفيد</option><option>الجمعية</option><option>الجهة المختصة</option><option>مقدم الخدمة</option></select></label></>}<label>تاريخ المتابعة<input type="date" value={followupDate} onChange={(event) => setFollowupDate(event.target.value)} /></label><div className="drawer-actions"><button className="secondary-btn" onClick={onClose}>إلغاء</button><button className="primary-btn" onClick={() => { const publicBody = type === "مراجعة مستند" ? "يوجد متطلب يحتاج تحديثًا لاستكمال متابعة طلبك." : "تمت متابعة طلبك، ولا يوجد إجراء مطلوب منك حاليًا."; onSave({ date: formatFollowupDate(followupDate), title: type === "مراجعة مستند" ? "مطلوب تحديث مستند" : "تم تحديث حالة طلبك", body: note || publicBody, beneficiaryBody: type === "مراجعة مستند" ? "نحتاج منك تحديث إثبات السكن لاستكمال متابعة طلبك." : "تمت متابعة طلبك، ولا يوجد إجراء مطلوب منك حاليًا.", action: needsAction === "نعم" ? nextAction : "لا يوجد إجراء آخر", responsible: needsAction === "نعم" ? responsible : item.owner }); }}>حفظ المتابعة <ArrowLeft size={16} /></button></div></aside></div>;
}

export function AssociationCasePage() {
  const [, params] = useRoute("/association/cases/:id");
  const [, navigate] = useLocation();
  const item = associationCases.find((candidate) => candidate.id === params?.id);
  const [drawerOpen, setDrawerOpen] = useState(false);
  const [escalated, setEscalated] = useState(false);
  const [history, setHistory] = useState(item?.history ?? []);
  if (!item) return <AppShell variant="association" eyebrow="الجمعية" title="الحالة غير موجودة" subtitle="لم نتمكن من العثور على الحالة ضمن نطاق الجمعية."><Link className="secondary-btn" href="/association">العودة إلى لوحة الجمعية <ArrowLeft size={16} /></Link></AppShell>;
  const stageAliases: Record<string, string> = { "استكمال المتطلبات": "استكمال الإجراءات", "التحقق من البيانات": "التحقق والاعتماد" }; const currentStage = stages.find((stage) => stage.title === item.stage || stage.title === stageAliases[item.stage]) ?? stages.find((stage) => stage.status === "قيد الإجراء") ?? stages[4];
  const handleSave = (entry: { date: string; title: string; body: string; beneficiaryBody?: string; action?: string; responsible?: string; internal?: boolean }) => { setHistory((current) => [entry, ...current]); setDrawerOpen(false); const publicAction = entry.action && entry.action !== "لا يوجد إجراء آخر" ? ` الخطوة التالية: ${entry.action} · المسؤول: ${entry.responsible ?? "الجمعية"}.` : ""; sessionStorage.setItem("yusr-association-update", JSON.stringify({ title: entry.title, body: `${entry.beneficiaryBody ?? entry.body}${publicAction}`, time: entry.date })); toast.success("تم تسجيل المتابعة"); };
  return <AppShell variant="association" eyebrow="ملف الحالة · عرض تشغيلي" title="ملف الحالة" subtitle="متابعة تشغيلية ضمن نطاق جمعية الإسكان التنموي – الرياض" actions={<Link className="secondary-btn" href="/association">العودة إلى الحالات <ArrowLeft size={16} /></Link>}>
    <section className="association-case-header"><div className="case-avatar large"><UserRound size={22} /></div><div><p className="eyebrow">{item.id}</p><h2>{item.name}</h2><div className="case-header-meta"><span><Flag size={14} /> {item.stage}</span><span><Clock3 size={14} /> {item.daysInStage} يومًا في المرحلة</span><span><CalendarDays size={14} /> آخر تحديث: {item.lastUpdated}</span></div></div><StatusBadge tone={toneForStatus(item.status)}>{escalated ? "تم طلب مراجعة" : item.status}</StatusBadge></section>
    <div className="association-case-grid"><main>
      <section className="association-case-panel"><div className="association-section-heading"><div><p className="eyebrow">مسار الطلب</p><h2>رحلة الحالة بالتفصيل</h2></div><span className="owner-chip"><UserRound size={14} /> المسؤول الحالي: {item.owner}</span></div><div className="association-stage-list">{stages.map((stage) => <article className={`association-stage-row ${stage.number === currentStage.number ? "current" : stage.status === "مكتمل" ? "done" : ""}`} key={stage.number}><div className="association-stage-marker">{stage.status === "مكتمل" ? <CheckCircle2 size={17} /> : stage.number === currentStage.number ? <span /> : <span className="hollow" />}</div><div className="association-stage-main"><div className="association-stage-title"><strong>{stage.number.toString().padStart(2, "0")} · {stage.title}</strong><StatusBadge tone={toneForStatus(stage.status)}>{stage.status}</StatusBadge></div><div className="association-stage-meta"><span>تاريخ الدخول: {stage.date || stage.estimatedNextDate}</span><span>المدة الحالية: {stage.number < currentStage.number ? stage.expectedDuration : stage.number === currentStage.number ? `${item.daysInStage} يومًا` : "لم تبدأ"}</span><span>المسؤول: {stage.number === currentStage.number ? item.owner : stage.status === "مكتمل" ? "الجهة المختصة" : "—"}</span><span>المتطلبات: {stage.number === currentStage.number ? item.requirement : stage.number < currentStage.number ? "مكتمل" : "لم يبدأ"}</span><span>آخر إجراء: {stage.number === currentStage.number ? item.lastAction : stage.number < currentStage.number ? "تم إكمال المرحلة" : "بانتظار بدء المرحلة"}</span></div><p>{stage.number === currentStage.number ? operationalSignals(item)[0] : stage.description}</p></div></article>)}</div></section>
      <section className="association-reason-card"><div className="reason-icon"><AlertTriangle size={20} /></div><div><p className="eyebrow">لماذا تحتاج الحالة تدخل؟</p><h2>سبب التنبيه</h2><p>{item.alert}.</p><small>هذه إشارة تشغيلية تجريبية تساعد الجمعية على اختيار الإجراء التالي، وليست قرارًا رسميًا.</small></div></section>
      <section className="association-next-card"><div><p className="eyebrow">الإجراء التالي</p><h2>{item.nextStep}</h2><p>المسؤول عن الخطوة الحالية: <strong>{item.owner}</strong></p></div><div className="next-actions"><button className="primary-btn" onClick={() => setDrawerOpen(true)}><MessageSquareText size={16} /> تسجيل متابعة</button>{!escalated && item.priority !== "عادية" && <button className="secondary-btn" onClick={() => { setEscalated(true); toast.success("تم طلب مراجعة الحالة"); }}>طلب مراجعة من الجهة</button>}</div></section>
      <section className="association-case-panel"><div className="association-section-heading compact"><div><p className="eyebrow">متطلبات الحالة</p><h2>ما الذي ينقص الملف؟</h2></div><span className="mock-tag">للاستخدام التشغيلي</span></div><div className="case-requirements"><div><CheckCircle2 size={17} /><span><strong>بيانات أفراد الأسرة</strong><small>مكتمل</small></span></div><div className={item.requirement === "ناقص" ? "missing" : ""}>{item.requirement === "ناقص" ? <AlertTriangle size={17} /> : <Clock3 size={17} />}<span><strong>إثبات السكن</strong><small>{item.requirement}</small></span></div><div><CheckCircle2 size={17} /><span><strong>البحث الاجتماعي</strong><small>مكتمل</small></span></div></div></section>
      <section className="association-case-panel"><div className="association-section-heading compact"><div><p className="eyebrow">سجل المتابعة</p><h2>ماذا حدث حتى الآن؟</h2></div><span className="log-count">{history.length} تحديثات</span></div><div className="association-history">{history.map((entry, index) => <article key={`${entry.date}-${entry.title}-${index}`}><div className="history-dot" /><div><time>{entry.date}</time><h3>{entry.title}</h3><p>{entry.body}</p>{(entry.action || entry.responsible) && <div className="history-meta"><span>الإجراء التالي: {entry.action ?? "لا يوجد إجراء آخر"}</span><span>المسؤول: {entry.responsible ?? "—"}</span></div>}</div></article>)}</div></section>
    </main><aside className="association-case-aside"><section className="case-aside-card"><p className="eyebrow">ملخص سريع</p><div className="aside-stat"><span>المرحلة</span><strong>{item.stage}</strong></div><div className="aside-stat"><span>مدة المرحلة</span><strong>{item.daysInStage} يومًا</strong></div><div className="aside-stat"><span>آخر إجراء</span><strong>{item.lastAction}</strong></div><div className="aside-stat"><span>المسؤول عن الخطوة</span><strong>{item.owner}</strong></div></section><section className="case-aside-card public-note"><CircleHelp size={18} /><div><strong>ما الذي يراه المستفيد؟</strong><p>يظهر له آخر تحديث مفيد والخطوة التالية فقط. لا تظهر له الملاحظات الداخلية للجمعية.</p></div></section><section className="case-aside-card"><p className="eyebrow">إشعار المستفيد</p><h3>بعد تسجيل المتابعة</h3><p className="aside-copy">يمكن إنشاء تحديث عام يظهر في إشعارات المستفيد دون كشف الملاحظات الداخلية.</p><span className="notification-preview"><BellRing size={15} /> تم تحديث حالة طلبك</span></section></aside></div>
    {drawerOpen && <FollowupDrawer item={item} onClose={() => setDrawerOpen(false)} onSave={handleSave} />}
  </AppShell>;
}
