/** أسلوب خريطة الاستقرار: لوحة الجهة تركز على نقاط التعطل ومسار الحالات بدل عرض جداول مكتظة غير قابلة للتصرف. */
import { ArrowLeft, Building2, CheckCircle2, ChevronLeft, ClipboardList, Filter, Search, TriangleAlert, Wrench } from "lucide-react";
import { useMemo, useState } from "react";
import { Link, useLocation } from "wouter";
import { toast } from "sonner";
import { AppShell } from "@/components/AppShell";
import { MetricCard } from "@/components/MetricCard";
import { StatusBadge } from "@/components/StatusBadge";
import { staffCases } from "@/data";

export function StaffPage() {
  const [, navigate] = useLocation();
  const [query, setQuery] = useState(""); const [filter, setFilter] = useState("الكل");
  const cases = useMemo(() => staffCases.filter((item) => (filter === "الكل" || item.stage === filter) && `${item.name} ${item.id}`.includes(query)), [filter, query]);
  return <AppShell eyebrow="عرض تشغيلي تجريبي" title="لوحة متابعة الجهة" subtitle="نظرة موحّدة على الحالات ومواطن التعطل ومتابعة الوحدات." actions={<button className="secondary-btn" onClick={() => navigate("/home")}>عرض المستفيد <ArrowLeft size={16} /></button>}>
    <div className="staff-demo-banner"><TriangleAlert size={15} /><strong>عرض تجريبي</strong><span>الأرقام والحالات المعروضة بيانات توضيحية وليست مؤشرات تشغيلية فعلية.</span></div><section className="staff-metrics"><MetricCard label="إجمالي الحالات" value="1,248" detail="ضمن نطاق المتابعة" icon={<ClipboardList size={18} />} tone="mint" onClick={() => setFilter("الكل")} /><MetricCard label="حالات تحتاج إجراء" value="86" detail="تحتاج تدخلًا" icon={<TriangleAlert size={18} />} tone="orange" onClick={() => setFilter("التخصيص")} /><MetricCard label="طلبات متوقفة" value="31" detail="في مرحلة التخصيص" icon={<Filter size={18} />} tone="stone" onClick={() => setFilter("التخصيص")} /><MetricCard label="تم التسليم" value="742" detail="وحدات نشطة" icon={<CheckCircle2 size={18} />} tone="green" onClick={() => setFilter("تم التسليم")} /><MetricCard label="بلاغات صيانة مفتوحة" value="49" detail="تحت المتابعة" icon={<Wrench size={18} />} tone="orange" onClick={() => setFilter("الصيانة")} /></section>
    <div className="staff-layout"><section className="cases-panel"><div className="panel-heading"><div><p className="eyebrow">قائمة العمل</p><h2>حالات المستفيدين</h2></div><Link className="text-link" href="/profile">فتح ملف أحمد <ChevronLeft size={17} /></Link></div><div className="case-toolbar"><label><Search size={17} /><input placeholder="ابحث باسم المستفيد أو رقم الحالة" value={query} onChange={(event) => setQuery(event.target.value)} /></label><select aria-label="تصفية الحالات حسب المرحلة" value={filter} onChange={(event) => setFilter(event.target.value)}><option>الكل</option><option>التخصيص</option><option>استكمال الإجراءات</option><option>التحقق والاعتماد</option><option>رفع الطلب</option><option>تم التسليم</option><option>الصيانة</option></select></div><div className="cases-table-wrap"><table className="cases-table"><thead><tr><th>المستفيد</th><th>المرحلة</th><th>اكتمال البيانات</th><th>مدة المرحلة</th><th>سبب التعطل / آخر إجراء</th><th>الإجراء المطلوب</th></tr></thead><tbody>{cases.map((item) => <tr key={item.id}><td><strong>{item.name}</strong><span>{item.id}</span></td><td><StatusBadge tone={item.tone as "success" | "warning" | "danger" | "info"}>{item.stage}</StatusBadge></td><td><div className="small-completion"><span>{item.complete}</span><i style={{ width: item.complete }} /></div></td><td>{item.duration}</td><td><span className="case-subtext">{item.cause}</span><span className="case-subtext">{item.lastAction}</span></td><td><button className="table-action" onClick={() => item.id === "SKN-2841" ? navigate("/profile") : undefined}>{item.action}</button></td></tr>)}</tbody></table>{!cases.length && <div className="empty-state"><Search size={25} /><strong>لم نجد حالة مطابقة</strong><p>جرّب البحث باسم أو رقم حالة آخر.</p></div>}</div></section><aside className="staff-side"><section className="bottleneck-card"><p className="eyebrow">إشارة تشغيلية</p><h2>نقاط التعطل</h2><div className="bottleneck-list"><div><span>التخصيص</span><i><b style={{ width: "100%" }} /></i><strong>31 حالة</strong></div><div><span>استكمال المتطلبات</span><i><b style={{ width: "74%" }} /></i><strong>23 حالة</strong></div><div><span>التعاقد</span><i><b style={{ width: "35%" }} /></i><strong>11 حالة</strong></div></div></section><section className="followup-card"><div className="followup-icon"><Building2 size={19} /></div><div><p className="eyebrow">الوحدات التي تحتاج متابعة</p><h3>12 وحدة</h3><p>تحتاج مراجعة عناصر الصيانة الدورية.</p></div><Link href="/unit/maintenance" className="text-link">عرض <ChevronLeft size={16} /></Link></section></aside></div><section className="impact-panel"><div><p className="eyebrow">الأثر المتوقع</p><h2>مؤشرات تستحق المتابعة</h2></div><div><span>متوسط زمن رحلة المستفيد</span><span>نسبة اكتمال ملفات المستفيدين</span><span>متوسط زمن معالجة بلاغات الصيانة</span><span>نسبة الحالات التي تعرف الإجراء التالي بوضوح</span></div></section>
  </AppShell>;
}
